In [1]:
# load the iris dataset as an example 
from sklearn.datasets import load_iris 
iris = load_iris() 

# store the feature matrix (X) and response vector (y) 
X = iris.data 
y = iris.target 

# store the feature and target names 
feature_names = iris.feature_names 
target_names = iris.target_names 

# printing features and target names of our dataset 
print("Feature names:", feature_names) 
print("Target names:", target_names) 

# X and y are numpy arrays 
print("\nType of X is:", type(X)) 

# printing first 5 input rows 
print("\nFirst 5 rows of X:\n", X[:5])


Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']

Type of X is: <class 'numpy.ndarray'>

First 5 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [3]:
import pandas as pd 

# reading csv file 
data = pd.read_csv('weather.csv') 

# shape of dataset 
print("Shape:", data.shape) 

# column names 
print("\nFeatures:", data.columns) 

# storing the feature matrix (X) and response vector (y) 
X = data[data.columns[:-1]] 
y = data[data.columns[-1]] 

# printing first 5 rows of feature matrix 
print("\nFeature matrix:\n", X.head()) 

# printing first 5 values of response vector 
print("\nResponse vector:\n", y.head())


Shape: (14, 5)

Features: Index(['Outlook', 'Temperature', 'Humidity', 'Windy', 'Play'], dtype='object')

Feature matrix:
     Outlook Temperature Humidity  Windy
0  overcast         hot     high  False
1  overcast        cool   normal   True
2  overcast        mild     high   True
3  overcast         hot   normal  False
4     rainy        mild     high  False

Response vector:
 0    yes
1    yes
2    yes
3    yes
4    yes
Name: Play, dtype: object


In [4]:
# load the iris dataset as an example 
from sklearn.datasets import load_iris 
iris = load_iris() 

# store the feature matrix (X) and response vector (y) 
X = iris.data 
y = iris.target 

# splitting X and y into training and testing sets 
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=1) 

# printing the shapes of the new X objects 
print(X_train.shape) 
print(X_test.shape) 

# printing the shapes of the new y objects 
print(y_train.shape) 
print(y_test.shape)


(90, 4)
(60, 4)
(90,)
(60,)


In [5]:
# load the iris dataset as an example 
from sklearn.datasets import load_iris 
iris = load_iris() 

# store the feature matrix (X) and response vector (y) 
X = iris.data 
y = iris.target 

# splitting X and y into training and testing sets 
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=1) 

# training the model on training set 
from sklearn.neighbors import KNeighborsClassifier 
knn = KNeighborsClassifier(n_neighbors=3) 
knn.fit(X_train, y_train) 

# making predictions on the testing set 
y_pred = knn.predict(X_test) 

# comparing actual response values (y_test) with predicted response values (y_pred) 
from sklearn import metrics 
print("kNN model accuracy:", metrics.accuracy_score(y_test, y_pred)) 

# making prediction for out of sample data 
sample = [[3, 5, 4, 2], [2, 3, 5, 4]] 
preds = knn.predict(sample) 
pred_species = [iris.target_names[p] for p in preds] 
print("Predictions:", pred_species) 

# saving the model 
from sklearn.externals import joblib 
joblib.dump(knn, 'iris_knn.pkl')


kNN model accuracy: 0.9833333333333333
Predictions: ['versicolor', 'virginica']


/home/rohitbhalerao/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


['iris_knn.pkl']

In [10]:
"""Important points to note from the above code:

    We create a knn classifier object using:

    knn = KNeighborsClassifier(n_neighbors=3)

    The classifier is trained using X_train data. The process is termed as fitting. We pass the feature matrix and the corresponding response vector.

    knn.fit(X_train, y_train)

    Now, we need to test our classifier on the X_test data. knn.predict method is used for this purpose. It returns the predicted response vector, y_pred.

    y_pred = knn.predict(X_test)

    Now, we are interested in finding the accuracy of our model by comparing y_test and y_pred. This is done using metrics module’s method accuracy_score:

    print(metrics.accuracy_score(y_test, y_pred))

    Consider the case when you want your model to make prediction on out of sample data. Then, the sample input can simply pe passed in the same way as we pass any feature matrix.

    sample = [[3, 5, 4, 2], [2, 3, 5, 4]]
    preds = knn.predict(sample)

    If you are not interested in training your classifier again and again and use the pre-trained classifier, one can save their classifier using joblib. All you need to do is:

    joblib.dump(knn, 'iris_knn.pkl')

    In case you want to load an already saved classifier, use the following method:

    knn = joblib.load('iris_knn.pkl')

"""

"Important points to note from the above code:\n\n    We create a knn classifier object using:\n\n    knn = KNeighborsClassifier(n_neighbors=3)\n\n    The classifier is trained using X_train data. The process is termed as fitting. We pass the feature matrix and the corresponding response vector.\n\n    knn.fit(X_train, y_train)\n\n    Now, we need to test our classifier on the X_test data. knn.predict method is used for this purpose. It returns the predicted response vector, y_pred.\n\n    y_pred = knn.predict(X_test)\n\n    Now, we are interested in finding the accuracy of our model by comparing y_test and y_pred. This is done using metrics module’s method accuracy_score:\n\n    print(metrics.accuracy_score(y_test, y_pred))\n\n    Consider the case when you want your model to make prediction on out of sample data. Then, the sample input can simply pe passed in the same way as we pass any feature matrix.\n\n    sample = [[3, 5, 4, 2], [2, 3, 5, 4]]\n    preds = knn.predict(sample)\n\n 